<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-03-07 19:40
=======
# Generated by Django 4.0.7 on 2023-03-08 17:48
>>>>>>> 7703d5906333721bd76046862895b54325ed1760

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=127)),
                ('number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=127)),
            ],
        ),
    ]
