# Generated by Django 4.0.7 on 2023-03-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='costumer',
        ),
    ]
