# Generated by Django 4.0.7 on 2023-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='costumer',
            field=models.BooleanField(default=False),
        ),
    ]
