# Generated by Django 4.0.7 on 2023-03-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.DeleteModel(
            name='OrdersProducts',
        ),
    ]
