<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-03-07 19:40
=======
# Generated by Django 4.0.7 on 2023-03-08 17:48
>>>>>>> 7703d5906333721bd76046862895b54325ed1760

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('category', models.CharField(max_length=127)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
