<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-03-07 19:40
=======
# Generated by Django 4.0.7 on 2023-03-08 17:48
>>>>>>> 7703d5906333721bd76046862895b54325ed1760

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
