# Generated by Django 4.0.7 on 2023-03-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
